title: thekingofcool's qqzone
favicon: /assets/favicon.ico
email: offweiboforawhile@proton.me
twitter_username: offXforawhile
github_username:  thekingofcool

# Build settings
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<-" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed
